### PR TITLE
Implemented dropdown actions using bootstrap and tether

### PR DESCRIPTION
**Pull request by ismcagdas**
This extension depends on bootstrap v.3.x (https://github.com/twbs/bootstrap) and tether (https://github.com/HubSpot/tether). So in order to use it, jquery.jtable.record-actions.js must be added after jtable and both bootstrap and tether libraries must be referenced.

Example definition of an actions field is:
````js
fields: {
    actions: { //'actions' is not a special name, but just another field name.
        type: 'record-actions', //introducing a new field type
        cssClass: 'btn btn-xs btn-primary blue', //this class is added to dropdown button if defined.
        text: '<i class="fa fa-cog"></i> Actions <span class="caret"></span>',//text or html can be used
        items: [{
            text: 'Edit record',
            action: function(data) {
                //TODO: Delete record
               //data parameter contains record property
            }
        }, {
            text: 'Delete record',
            action: function(data) {
                //TODO: Edit record
               //data parameter contains record property
            }
        }]
    },
    //...other fields
}
````

Also, if you want to show/hide a dropdown conditionally, you can define a function named "**visible**" to your dropdown list item which returns a boolean. If all dropdown list items are invisible, then main dropdown button becomes invisible as well.

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks a lot.

**Comment by dasguptahirak** [comment]
@ismcagdas 
Please guide how to use. 
Share some example.

**Comment by ismcagdas** [comment]
Hi,

The comment above contains an example usage, did you try it ?
Or are you asking a full example of it ?

**Comment by dasguptahirak** [comment]
@ismcagdas 
Yes I need full example.

**Comment by ismcagdas** [comment]
Hi,

I don't have time for preparing full example right now but yhe usage is very simple.
* Just include  jquery.jtable.record-actions.js after jtable.
* Also include bootstrap and tether javascript files before jtable.
* and add actions field defined above into your jtable definition, that's it.

Thanks.

**Comment by cangunaydin** [comment]
Hello,
It can be also good to send the jquery object reference for the anchor tag to the action method. I am trying to open a child table which needs a reference for the closest table row. or is there another way that i can get the reference? 

Thanks.

**Comment by syntaro** [comment]
Hello,, Im from japan.

Thank you for share your code.
and my 2024 version here.PersonActions.php

`<?php

try
{
	//Open database connection
	$mysqluser = '';
	$mysqlpass = '';
 	$dbh = new PDO('mysql:host=localhost;dbname=jtabletestdb', $mysqluser, $mysqlpass);
	//$dbh->query('SET NAMES sjis');

	//Getting records (listAction)
	if($_GET["action"] == "list")
	{
		//Get records from database
		$result = $dbh->query("SELECT * FROM people");
		
		//Add all records to an array
		$rows = array();
		foreach($result as $row)
		{
		    $rows[] = $row;
		}

		//Return result to jTable
		$jTableResult = array();
		$jTableResult['Result'] = "OK";
		$jTableResult['Records'] = $rows;
		print json_encode($jTableResult);
	}
	//Creating a new record (createAction)
	else if($_GET["action"] == "create")
	{
		//Insert record into database
		$result = $dbh->query("INSERT INTO people(Name, Age, RecordDate) VALUES('" . $_POST["Name"] . "', " . $_POST["Age"] . ",now())");
		
		//Get last inserted record (to return to jTable)
		$result = $dbh->query("SELECT * FROM people WHERE PersonId = LAST_INSERT_ID()");
		//Add all records to an array
		$rows = array();
		foreach($result as $row)
		{
		    $rows = $row;
		}

		//Return result to jTable
		$jTableResult = array();
		$jTableResult['Result'] = "OK";
		$jTableResult['Record'] = $rows;
		print json_encode($jTableResult);
	}
	//Updating a record (updateAction)
	else if($_GET["action"] == "update")
	{
		//Update record in database
		$result = $dbh->query("UPDATE people SET Name = '" . $_POST["Name"] . "', Age = " . $_POST["Age"] . " WHERE PersonId = " . $_POST["PersonId"]);

		//Return result to jTable
		$jTableResult = array();
		$jTableResult['Result'] = "OK";
		print json_encode($jTableResult);
	}
	//Deleting a record (deleteAction)
	else if($_GET["action"] == "delete")
	{
		//Delete from database
		$result = $dbh->query("DELETE FROM people WHERE PersonId = " . $_POST["PersonId"]);

		//Return result to jTable
		$jTableResult = array();
		$jTableResult['Result'] = "OK";
		print json_encode($jTableResult);
	}

	//Close database connection
	$dbh = null;

}
catch(Exception $ex)
{
    //Return error message
	$jTableResult = array();
	$jTableResult['Result'] = "ERROR";
	$jTableResult['Message'] = $ex->getMessage();
	print json_encode($jTableResult);
}
	
?>
`

**Pull request merged**
